data:
  batch_size: 4
  dataset:
    name: ALOSDataset
    trainpath: $TMPDIR/data
  transform: LogAmplitude, RealImaginary
  img_size: 64
  img_stride: 64
  num_workers: 0
  valid_ratio: 0.15
  test_ratio: 0.15
  crop:
    end_col: 1512
    end_row: 3512
    start_col: 1000
    start_row: 3000
logging:
  logdir: ./logs
  backend: aim
  aim:
    experiment: sf_alos2
loss:
  name: ComplexMSELoss
model:
  activation: ReLU
  channels_ratio: 16
  class: AutoEncoderWD
  res: true
  projection:
    class: ModCtoR
    global: true
  downsampling: LPD_F
  upsampling: LPU_F
  latent_dim: Null
  dropout: 0
  normalization:
    method: BatchNorm
    track_running_stats: false
  num_layers: 4
  gumbel_tau:
    start_value: 10
    gamma: 0.1
    start_decay_epoch: 10
    min_value: 0.00001
nepochs: 1
optim:
  algo: AdamW
  params:
    lr: 0.001
    weight_decay: 0
scheduler:
  algo: StepLR
  params:
    step_size: 10000
    gamma: 0.9
pretrained: false
world_size: 1
dtype: float64
