data:
  batch_size: 64
  dataset:
    name: ALOSDataset
    trainpath: ../../datasets/SAN_FRANCISCO_ALOS2
  transform: LogAmplitude
  img_size: 64
  img_stride: 64
  num_workers: 4
  valid_ratio: 0.15
  test_ratio: 0.15
  crop:
    end_col: 3200
    end_row: 7500
    start_col: 1000
    start_row: 3000
logging:
  logdir: ./logs
  wandb:
    entity: equivariant_cvnn
    project: sf_alos2
loss:
  name: ComplexMSELoss
model:
  activation: modReLU
  channels_ratio: 16
  class: AutoEncoderWD
  res: false
  projection:
    class: ModCtoR
    global: true
  downsampling: StridedConv
  upsampling: ConvTranspose
  latent_dim: Null
  dropout: 0
  normalization:
    method: BatchNorm
    track_running_stats: false
  num_layers: 4
nepochs: 500
optim:
  algo: AdamW
  params:
    lr: 0.0005
    weight_decay: 0.0001
scheduler:
  algo: StepLR
  params:
    step_size: 10000
    gamma: 0.9
pretrained: false
world_size: 4
dtype: complex64
