# Task-specific configuration for Classification task
task: classification

# Data configuration
data:
  recompute_statistics: True
  shuffle: True
  batch_size: 1024
  dataset:
    name: S1SLC
    trainpath: $TMPDIR/data
    patch_size: 64
    patch_stride: 64
  num_workers: 4
  valid_ratio: 0.15
  test_ratio: 0.15
  transforms:
    - name: logamplitude
    - name: realimaginary

# Model configuration
model:
  activation: ReLU
  channels_width: 16
  class: ResNet
  layer_mode: real
  num_layers: 4
  num_blocks: 1
  normalization_layer: batch
  downsampling_layer: LPD
  latent_dim: 128
  residual: True
  dropout: 0.1
  projection:
    class: NoCtoR
    global: true
    softmax: Softmax
  gumbel_tau:
    start_value: 5
    gamma: 0.1
    start_decay_epoch: 5
    min_value: 0.00001

evaluation:
  check_invariance: True
  domain: spatial

# Logging configuration
logging:
  logdir: ./logs
  wandb:
    entity: equivariant_cvnn
    project: s1slc
    name: resnet_rvnn_lps

# Loss configuration
loss:
  name: FocalLoss
  gamma: 3

# Training configuration
training:
  nepochs: 100
  optim:
    algo: AdamW
    params:
      lr: 0.01
      weight_decay: 0.0005
  scheduler:
    algo: StepLR
    params:
      step_size: 1000
      gamma: 1.0

# Data type configuration
dtype: float64